-- MySQL Script generated by MySQL Workbench
-- Sun Aug  8 14:23:43 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema scsm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema scsm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `scsm` DEFAULT CHARACTER SET utf8mb4 ;
USE `scsm` ;

-- -----------------------------------------------------
-- Table `scsm`.`area_formacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scsm`.`area_formacion` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `scsm`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scsm`.`estado` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `scsm`.`cambio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scsm`.`cambio` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `estado_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cambios_estado1_idx` (`estado_id` ASC) VISIBLE,
  CONSTRAINT `fk_cambios_estado1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `scsm`.`estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `scsm`.`facultad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scsm`.`facultad` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `scsm`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scsm`.`departamento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `facultad_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_departamento_facultad1_idx` (`facultad_id` ASC) VISIBLE,
  CONSTRAINT `fk_departamento_facultad1`
    FOREIGN KEY (`facultad_id`)
    REFERENCES `scsm`.`facultad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `scsm`.`programa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scsm`.`programa` (
  `codigo` INT(11) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `departamento_id` INT(11) NOT NULL,
  `imagen` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_programa_facultad1_idx` (`departamento_id` ASC) VISIBLE,
  CONSTRAINT `fk_programa_facultad1`
    FOREIGN KEY (`departamento_id`)
    REFERENCES `scsm`.`departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `scsm`.`pensum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scsm`.`pensum` (
  `codigo` INT(11) NOT NULL,
  `programa_codigo` INT(11) NOT NULL,
  `fecha_inicio_vigencia` DATE NULL DEFAULT NULL,
  `fecha_fin_vigencia` DATE NULL DEFAULT NULL,
  `estado_visualizacion` TINYINT(4) NOT NULL DEFAULT 0,
  PRIMARY KEY (`codigo`, `programa_codigo`),
  INDEX `fk_pensum_programa1_idx` (`programa_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_pensum_programa1`
    FOREIGN KEY (`programa_codigo`)
    REFERENCES `scsm`.`programa` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `scsm`.`tipo_materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scsm`.`tipo_materia` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `scsm`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scsm`.`materia` (
  `codigo` INT(11) NOT NULL,
  `pensum_codigo` INT(11) NOT NULL,
  `programa_codigo` INT(11) NOT NULL,
  `tipo_id` INT(11) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `creditos` INT(11) NOT NULL,
  `semestre` INT(11) NOT NULL,
  `ht` INT(11) NOT NULL,
  `hp` INT(11) NOT NULL,
  `hti` INT(11) NOT NULL,
  `cr` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`, `pensum_codigo`),
  INDEX `fk_materia_pensum1_idx` (`pensum_codigo` ASC, `programa_codigo` ASC) VISIBLE,
  INDEX `tipo_id` (`tipo_id` ASC) VISIBLE,
  CONSTRAINT `fk_materia_pensum1`
    FOREIGN KEY (`pensum_codigo` , `programa_codigo`)
    REFERENCES `scsm`.`pensum` (`codigo` , `programa_codigo`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `materia_ibfk_1`
    FOREIGN KEY (`tipo_id`)
    REFERENCES `scsm`.`tipo_materia` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `scsm`.`microcurriculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scsm`.`microcurriculo` (
  `materia_codigo` INT(11) NOT NULL,
  `materia_pensum_codigo` INT(11) NOT NULL,
  `area_de_formacion_id` INT(11) NOT NULL,
  PRIMARY KEY (`materia_codigo`, `materia_pensum_codigo`),
  INDEX `fk_microcurriculo_area_de_formacion1_idx` (`area_de_formacion_id` ASC) VISIBLE,
  INDEX `fk_microcurriculo_materia1_idx` (`materia_codigo` ASC, `materia_pensum_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_microcurriculo_area_de_formacion1`
    FOREIGN KEY (`area_de_formacion_id`)
    REFERENCES `scsm`.`area_formacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_microcurriculo_materia1`
    FOREIGN KEY (`materia_codigo` , `materia_pensum_codigo`)
    REFERENCES `scsm`.`materia` (`codigo` , `pensum_codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 97
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `scsm`.`tipo_seccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scsm`.`tipo_seccion` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `scsm`.`seccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scsm`.`seccion` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `tipo_seccion_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_seccion_tipo_seccion1_idx` (`tipo_seccion_id` ASC) VISIBLE,
  CONSTRAINT `fk_seccion_tipo_seccion1`
    FOREIGN KEY (`tipo_seccion_id`)
    REFERENCES `scsm`.`tipo_seccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `scsm`.`seccion_microcurriculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scsm`.`seccion_microcurriculo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `seccion_id` INT(11) NOT NULL,
  `editable` TINYINT(4) NOT NULL DEFAULT 0,
  `microcurriculo_materia_codigo` INT(11) NOT NULL,
  `microcurriculo_materia_pensum_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_seccion_microcurriculo_seccion1_idx` (`seccion_id` ASC) VISIBLE,
  INDEX `fk_seccion_microcurriculo_microcurriculo1_idx` (`microcurriculo_materia_codigo` ASC, `microcurriculo_materia_pensum_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_seccion_microcurriculo_microcurriculo1`
    FOREIGN KEY (`microcurriculo_materia_codigo` , `microcurriculo_materia_pensum_codigo`)
    REFERENCES `scsm`.`microcurriculo` (`materia_codigo` , `materia_pensum_codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_seccion_microcurriculo_seccion1`
    FOREIGN KEY (`seccion_id`)
    REFERENCES `scsm`.`seccion` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 19326
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `scsm`.`contenido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scsm`.`contenido` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `texto` VARCHAR(6000) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `cantidad_items_lista` INT(11) NOT NULL,
  `seccion_microcurriculo_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contenido_seccion_microcurriculo1_idx` (`seccion_microcurriculo_id` ASC) VISIBLE,
  CONSTRAINT `fk_contenido_seccion_microcurriculo1`
    FOREIGN KEY (`seccion_microcurriculo_id`)
    REFERENCES `scsm`.`seccion_microcurriculo` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 16858
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `scsm`.`docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scsm`.`docente` (
  `codigo` INT(11) NOT NULL,
  `programa_codigo` INT(11) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `estado` TINYINT(4) NOT NULL DEFAULT 1,
  `imagen` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_docente_programa1_idx` (`programa_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_docente_programa1`
    FOREIGN KEY (`programa_codigo`)
    REFERENCES `scsm`.`programa` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `scsm`.`tabla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scsm`.`tabla` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `scsm`.`encabezado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scsm`.`encabezado` (
  `columna` INT(11) NOT NULL,
  `tabla_id` INT(11) NOT NULL,
  `encabezado` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`tabla_id`, `columna`),
  INDEX `fk_encabezado_tabla1_idx` (`tabla_id` ASC) VISIBLE,
  CONSTRAINT `fk_encabezado_tabla1`
    FOREIGN KEY (`tabla_id`)
    REFERENCES `scsm`.`tabla` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5040
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `scsm`.`equivalencia_materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scsm`.`equivalencia_materia` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `equivalencia_materia` INT(11) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `materia_codigo` INT(11) NOT NULL,
  `materia_pensum_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_equivalencia_materia_materia1_idx` (`materia_codigo` ASC, `materia_pensum_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_equivalencia_materia_materia1`
    FOREIGN KEY (`materia_codigo` , `materia_pensum_codigo`)
    REFERENCES `scsm`.`materia` (`codigo` , `pensum_codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 13001
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `scsm`.`materia_periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scsm`.`materia_periodo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo_materia` INT(11) NOT NULL,
  `materia_pensum_codigo` INT(11) NOT NULL,
  `anio` INT(11) NOT NULL,
  `periodo` INT(11) NOT NULL,
  INDEX `fk_materia_periodo_materia1_idx` (`codigo_materia` ASC, `materia_pensum_codigo` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_materia_periodo_materia1`
    FOREIGN KEY (`codigo_materia` , `materia_pensum_codigo`)
    REFERENCES `scsm`.`materia` (`codigo` , `pensum_codigo`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `scsm`.`materia_periodo_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scsm`.`materia_periodo_grupo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `grupo` VARCHAR(2) NOT NULL,
  `docente_codigo` INT(11) NOT NULL,
  `materia_periodo_id` INT NOT NULL,
  INDEX `fk_materia_periodo_grupo_docente1_idx` (`docente_codigo` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_materia_periodo_grupo_materia_periodo1_idx` (`materia_periodo_id` ASC) VISIBLE,
  CONSTRAINT `fk_materia_periodo_grupo_docente1`
    FOREIGN KEY (`docente_codigo`)
    REFERENCES `scsm`.`docente` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materia_periodo_grupo_materia_periodo1`
    FOREIGN KEY (`materia_periodo_id`)
    REFERENCES `scsm`.`materia_periodo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `scsm`.`prerrequisito_materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scsm`.`prerrequisito_materia` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `materia_codigo` INT(11) NOT NULL,
  `materia_pensum_codigo` INT(11) NOT NULL,
  `materia_codigo_prerreq` INT(11) NOT NULL,
  `materia_pensum_codigo_prerreq` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_prerrequisito_materia_materia1_idx` (`materia_codigo` ASC, `materia_pensum_codigo` ASC) VISIBLE,
  INDEX `fk_prerrequisito_materia_materia2_idx` (`materia_codigo_prerreq` ASC, `materia_pensum_codigo_prerreq` ASC) VISIBLE,
  CONSTRAINT `fk_prerrequisito_materia_materia1`
    FOREIGN KEY (`materia_codigo` , `materia_pensum_codigo`)
    REFERENCES `scsm`.`materia` (`codigo` , `pensum_codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_prerrequisito_materia_materia2`
    FOREIGN KEY (`materia_codigo_prerreq` , `materia_pensum_codigo_prerreq`)
    REFERENCES `scsm`.`materia` (`codigo` , `pensum_codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4540
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `scsm`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scsm`.`rol` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `scsm`.`seccion_cambio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scsm`.`seccion_cambio` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cambio_id` INT(11) NOT NULL,
  `seccion_microcurriculo_id_nuevo` INT(11) NOT NULL,
  `seccion_microcurriculo_id_antigua` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_seccion_cambio_cambio1_idx` (`cambio_id` ASC) VISIBLE,
  INDEX `fk_seccion_cambio_seccion_microcurriculo1_idx` (`seccion_microcurriculo_id_nuevo` ASC) VISIBLE,
  INDEX `fk_seccion_cambio_seccion_microcurriculo2_idx` (`seccion_microcurriculo_id_antigua` ASC) VISIBLE,
  CONSTRAINT `fk_seccion_cambio_cambio1`
    FOREIGN KEY (`cambio_id`)
    REFERENCES `scsm`.`cambio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seccion_cambio_seccion_microcurriculo1`
    FOREIGN KEY (`seccion_microcurriculo_id_nuevo`)
    REFERENCES `scsm`.`seccion_microcurriculo` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seccion_cambio_seccion_microcurriculo2`
    FOREIGN KEY (`seccion_microcurriculo_id_antigua`)
    REFERENCES `scsm`.`seccion_microcurriculo` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `scsm`.`tipo_seccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scsm`.`tipo_seccion` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `scsm`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scsm`.`usuario` (
  `docente_codigo` INT(11) NOT NULL,
  `rol_id` INT(11) NOT NULL,
  `clave` VARCHAR(120) NOT NULL,
  INDEX `fk_Usuario_Rol1_idx` (`rol_id` ASC) VISIBLE,
  PRIMARY KEY (`docente_codigo`),
  CONSTRAINT `fk_Usuario_Rol1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `scsm`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_docente1`
    FOREIGN KEY (`docente_codigo`)
    REFERENCES `scsm`.`docente` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `scsm`.`unidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scsm`.`unidad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `num` INT NOT NULL,
  `nombre` VARCHAR(200) NOT NULL,
  `horas_presencial` INT NOT NULL,
  `horas_independiente` INT NOT NULL,
  `microcurriculo_materia_codigo` INT(11) NOT NULL,
  `microcurriculo_materia_pensum_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_unidad_microcurriculo1_idx` (`microcurriculo_materia_codigo` ASC, `microcurriculo_materia_pensum_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_unidad_microcurriculo1`
    FOREIGN KEY (`microcurriculo_materia_codigo` , `microcurriculo_materia_pensum_codigo`)
    REFERENCES `scsm`.`microcurriculo` (`materia_codigo` , `materia_pensum_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `scsm`.`contenido_unidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scsm`.`contenido_unidad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `unidad_id` INT NOT NULL,
  `contenido` VARCHAR(2000) NOT NULL,
  `trabajo_presencial` VARCHAR(2000) NULL,
  `trabajo_independiente` VARCHAR(2000) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contenido_unidad_unidad1_idx` (`unidad_id` ASC) VISIBLE,
  CONSTRAINT `fk_contenido_unidad_unidad1`
    FOREIGN KEY (`unidad_id`)
    REFERENCES `scsm`.`unidad` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `scsm`.`cumplimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scsm`.`cumplimiento` (
  `materia_periodo_grupo_id` INT(11) NOT NULL,
  `contenido_unidad_id` INT NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT 0,
  INDEX `fk_cumplimiento_materia_periodo_grupo1_idx` (`materia_periodo_grupo_id` ASC) VISIBLE,
  PRIMARY KEY (`materia_periodo_grupo_id`, `contenido_unidad_id`),
  INDEX `fk_cumplimiento_contenido_unidad1_idx` (`contenido_unidad_id` ASC) VISIBLE,
  CONSTRAINT `fk_cumplimiento_materia_periodo_grupo1`
    FOREIGN KEY (`materia_periodo_grupo_id`)
    REFERENCES `scsm`.`materia_periodo_grupo` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cumplimiento_contenido_unidad1`
    FOREIGN KEY (`contenido_unidad_id`)
    REFERENCES `scsm`.`contenido_unidad` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scsm`.`tabla_seccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scsm`.`tabla_seccion` (
  `seccion_microcurriculo_id` INT(11) NOT NULL,
  `tabla_id` INT(11) NOT NULL,
  PRIMARY KEY (`seccion_microcurriculo_id`),
  INDEX `fk_tabla_seccion_seccion_microcurriculo1_idx` (`seccion_microcurriculo_id` ASC) VISIBLE,
  INDEX `fk_tabla_seccion_tabla1_idx` (`tabla_id` ASC) VISIBLE,
  CONSTRAINT `fk_tabla_seccion_seccion_microcurriculo1`
    FOREIGN KEY (`seccion_microcurriculo_id`)
    REFERENCES `scsm`.`seccion_microcurriculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tabla_seccion_tabla1`
    FOREIGN KEY (`tabla_id`)
    REFERENCES `scsm`.`tabla` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
